version: "3.9"

services:
  db:
    build: ./database
    image: drapsag/woody_db:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'

  api:
    build: ./api
    image: drapsag/woody_api:latest
    restart: always
    links:
      - "db"

  front:
    build: ./front
    image: drapsag/woody_front:latest

  reverse:
    build: ./reverse
    image: drapsag/woody_rp:latest
    ports:
      - "80:8080"
    depends_on:
      - front
      - api


  redis:
    image: redis
    ports:
    - '6379:6379'