#version: "3.9"

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    # networks:
    #   - woodynet

  rabbitmq:
    image: rabbitmq:latest

  db:
    build: ./db
    image: drapsag/woody_db:latest
    deploy:
      replicas: 1
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=woody
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
    # networks:
    #   - woodynet


  api_misc:
    build: ./api_misc
    image: drapsag/woody_api_misc:latest
    restart: always
    # networks:
    #   - woodynet
    depends_on:
      - redis

  api:
    build: ./api
    image: drapsag/woody_api:latest
    restart: always
    links:
      - "db"
    # networks:
    #   - woodynet
    depends_on:
      - db

  api_order:
    build: ./api_order
    image: drapsag/woody_api_order:latest
    restart: always
    # networks:
    #   - woodynet
    depends_on:
      - rabbitmq

  front:
    build: ./front
    image: drapsag/woody_front:latest    
    # networks:
    #   - woodynet

  reverse:
    build: ./reverse
    image: drapsag/woody_reverse:latest    
    ports:
      - "80:8080"
    depends_on:
      - front
      - api
      - api_misc
    # networks:
    #   - woodynet


# networks:
#   woodynet:

