version: "3"
name: tp5compose

services:
  nginx: 
    image: mon-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network

  php:
    image: mon-php
    volumes:
      - ./html:/var/www/html
    networks:
      - my_network

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    networks:
      - my_network

networks:
  my_network:
