#version: "3"
name: tp6compose

services:
  nginx: 
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certificate/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certificate/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/letsencrypt/:/etc/letsencrypt/
    networks:
      - dmz

  php:
    build: php
    volumes:
      - ./html:/var/www/html/
    env_file: 
      - db.env
    networks:
      - dmz
      - db_net

  mariadb:
    image: mariadb:11.1
    env_file:
      - db/root.env
      - db.env
    volumes: 
      - db_data:/var/lib/mysql/
      - ./db/sql/:/docker-entrypoint-initdb.d/
      - ./db/conf.d/my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf
    networks:
      - db_net

networks:
  dmz:
  db_net:

volumes:
  db_data:
